version: "3.9"


services:
  express:
    container_name: express
    restart: unless-stopped
    build:
      context: ./express
    user: "node"
    ports: 
      - 3000:3000
    volumes:
      - ./express:/app
      - ./express/node_modules:/app/node_modules
    command:
      - nodemon
      - server.js
    networks:
      - app_net
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/app_db
      DB_NAME: app_db
  
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes: 
  mongo_data: {}
