services:
  express:
    container_name: express
    env_file: .env
    restart: unless-stopped
    build:
      context: ./express
      dockerfile: Dockerfile
    user: "node"
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./express:/app
      - ./express/node_modules:/app/node_modules
    command:
      - nodemon
      - server.js
    networks:
      - app_net
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/app_db
      DB_NAME: app_db
  
  nginx:
    image: reverse-proxy
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - app_net

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net
    command: mongod --quiet --logpath /dev/null

networks:
  app_net:
    driver: bridge

volumes: 
  mongo_data: {}
